// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Solution.DataBase;

#nullable disable

namespace Solution.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Solution.Database.Entities.BillEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillNumber")
                        .IsUnique();

                    b.ToTable("Bill");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillNumber = "BILL-2025-001",
                            DateIssued = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BillNumber = "BILL-2025-002",
                            DateIssued = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BillNumber = "BILL-2025-003",
                            DateIssued = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Solution.Database.Entities.BillItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItem");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillId = 1,
                            Name = "Laptop",
                            Quantity = 2,
                            UnitPrice = 150000
                        },
                        new
                        {
                            Id = 2,
                            BillId = 1,
                            Name = "Mouse",
                            Quantity = 3,
                            UnitPrice = 5000
                        },
                        new
                        {
                            Id = 3,
                            BillId = 2,
                            Name = "Monitor",
                            Quantity = 1,
                            UnitPrice = 80000
                        },
                        new
                        {
                            Id = 4,
                            BillId = 2,
                            Name = "Keyboard",
                            Quantity = 2,
                            UnitPrice = 15000
                        },
                        new
                        {
                            Id = 5,
                            BillId = 3,
                            Name = "Headset",
                            Quantity = 1,
                            UnitPrice = 25000
                        },
                        new
                        {
                            Id = 6,
                            BillId = 3,
                            Name = "USB Cable",
                            Quantity = 5,
                            UnitPrice = 2000
                        });
                });

            modelBuilder.Entity("Solution.Database.Entities.BillItemEntity", b =>
                {
                    b.HasOne("Solution.Database.Entities.BillEntity", "Bill")
                        .WithMany("BillItems")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Solution.Database.Entities.BillEntity", b =>
                {
                    b.Navigation("BillItems");
                });
#pragma warning restore 612, 618
        }
    }
}
